[package]
name = "project_prismarine"
version = "0.0.1-R"
authors = ["Prismarine Bluefall <sbisonol@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
log = "0.4.8"
pretty_env_logger = "0.3.1"

[dependencies.serenity]
version = "0.7.0"
features = ["framework", "standard_framework"]